# Practical_6: Numpy

In [5]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [9]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [11]:
b = np.linspace(0,5,10)
b

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [13]:
c = np.eye(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [15]:
rand_matrix= np.random.rand(4,4)
rand_matrix

array([[0.43187977, 0.01977001, 0.07799016, 0.4847822 ],
       [0.51966159, 0.77432214, 0.11685705, 0.00739997],
       [0.69143167, 0.95911066, 0.5928287 , 0.09182471],
       [0.77980184, 0.95543239, 0.80624097, 0.82173772]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [17]:
arr_shape = np.arange(1,5)
print(arr_shape.shape)
#arr_shape = np.shape()

(4,)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [19]:
ele = np.arange(0,16).reshape(4,4)
ele

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [21]:
ele_type = np.arange(0,5)
print(type(ele_type))

<class 'numpy.ndarray'>



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [23]:
arr = np.arange(1,101)
even_nbr = arr[arr % 2 == 0]
print(even_nbr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [25]:
p = np.random.randint(10,50 ,size= (6,6))
p

array([[36, 24, 45, 48, 49, 31],
       [19, 42, 20, 33, 42, 34],
       [34, 13, 16, 45, 47, 15],
       [21, 16, 17, 46, 21, 41],
       [30, 37, 23, 22, 25, 42],
       [24, 35, 31, 41, 43, 49]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [27]:
arr = np.arange(1,26).reshape(5,5)
arr
submatrix = arr[0:3,0:3]
submatrix

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [29]:
sum_arr = np.arange(1,30)
print(np.sum(sum_arr))

435



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [31]:
z = np.arange(0,17)
mean = np.mean(z)
median = np.median(z)
st_deviation = np.std(z)
print(mean)
print(median)
print(st_deviation)

8.0
8.0
4.898979485566356



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [33]:
values = np.arange(2,22)
max_nbr = np.max(values)
min_nbr = np.min(values)
print("maximum value is:", max_nbr)
print("minimum value is:",min_nbr)

maximum value is: 21
minimum value is: 2



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [35]:
val = np.random.randint(0,30 , size = 20)
max_int = np.argmax(val)
print(val)
print("Index of max value:", max_int)

[ 9  9 21 27 13 29 13 21  4  1 29  0  9 17  6  1 14 29 17 10]
Index of max value: 5



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [37]:
z = np.arange(10)
reverse_z = z[::-1]
reverse_z


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [39]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
result = matrix1 * matrix2
result

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [41]:
matr =  np.array([2,4,5,1,0])
diagonal_matrix = np.diag(matr)
diagonal_matrix

array([[2, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [43]:
h = np.array([[2,3,1],
             [5,4,2],
             [8,6,0]])
g = np.array([[4,3,1],
             [5,8,7],
             [0,0,1]])
result = np.multiply(h,g)
result

array([[ 8,  9,  1],
       [25, 32, 14],
       [ 0,  0,  0]])


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [45]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
flat_arr = arr_2d.flatten()
flat_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [47]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

stacked = np.vstack((a, b))
stacked

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [194]:
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

stacked = np.hstack((m, n))
stacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [196]:
arr = np.array([0, 1, 2, 3, 4, 5])
splitted = np.split(arr, 3)
splitted

[array([0, 1]), array([2, 3]), array([4, 5])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [198]:
random_arr = np.round(np.random.rand(20), 2)
random_arr

array([0.87, 0.53, 0.07, 0.42, 0.55, 0.28, 0.82, 0.33, 0.48, 0.16, 0.3 ,
       0.47, 0.26, 0.73, 0.47, 0.48, 0.85, 0.81, 0.95, 0.72])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [202]:
ele = np.array([1,2,3,3,1,4,5,6,6,7,9])
unique_ele = np.unique(ele)
unique_ele

array([1, 2, 3, 4, 5, 6, 7, 9])


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [204]:
arr = np.array([3, 12, 7, 15, 9])
arr[arr < 10] = 10
print(arr)

[10 12 10 15 10]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [208]:
p = np.array([1,3,4,5,7,8])
cumu_sum = np.cumsum(p)
cumu_sum

array([ 1,  4,  8, 13, 20, 28])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [210]:
arr = np.array([0, 1, 2, 0, 3, 0, 4])
non_zero_count = np.count_nonzero(arr)
print("Array:", arr)
print("Number of non-zero elements:", non_zero_count)

Array: [0 1 2 0 3 0 4]
Number of non-zero elements: 4



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [212]:
y = np.random.randint(0, 20, size=10)
y_sorted = np.sort(y)
y_sorted

array([ 0,  1,  2,  6, 13, 13, 14, 17, 18, 19])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [218]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Matrix:\n", matrix)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sums: [ 6 15 24]
Column-wise sums: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [220]:
arr = np.random.randint(0, 100, size=(3, 4))
print("Original array:\n", arr)
# Normalize the array to range [0, 1]
arr_norm = (arr - arr.min()) / (arr.max() - arr.min())
print("\nNormalized array:\n", arr_norm)


Original array:
 [[ 2 14 95 10]
 [30 41 64 51]
 [16 76 52 13]]

Normalized array:
 [[0.         0.12903226 1.         0.08602151]
 [0.30107527 0.41935484 0.66666667 0.52688172]
 [0.15053763 0.79569892 0.53763441 0.11827957]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [222]:
a = np.array([1,2,3])
b = np.array([3,9,6])
dot_pro = np.dot(a,b)
dot_pro

39


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [224]:
matrix = np.array([[1, 2],
                   [4, 5]])
trace_matrix = np.trace(matrix)
trace_matrix

6


---

### Exercise 34:
Create a 2D array and swap two rows.


In [232]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:\n", arr)
arr[[0, 2]] = arr[[2, 0]]
print("\nArray after swapping row 0 and row 1:\n", arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping row 0 and row 1:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [234]:
arr = np.array([1, 2, 3, 4, 5])
print("Original 1D array:\n", arr)
col_vector = arr.reshape(-1, 1)
print("\nColumn vector:\n", col_vector)
print("Shape:", col_vector.shape)

Original 1D array:
 [1 2 3 4 5]

Column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Shape: (5, 1)



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [228]:
matrix = np.array([[1,2,3],
                 [2,1,4],
                 [7,9,0]])
det_matrix = np.linalg.det(matrix)
det_matrix

52.999999999999986


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [236]:
matrix = np.array([[4, 2],
                   [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Matrix:
 [[4 2]
 [1 3]]

Eigenvalues:
 [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [238]:
# Coefficient matrix (A)
A = np.array([[2, 3],
              [5, 1]])

# Constants vector (b)
b = np.array([8, 9])

# Solve for [x, y]
solution = np.linalg.solve(A, b)

print("Solution [x, y]:", solution)

Solution [x, y]: [1.46153846 1.69230769]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [240]:
arr = np.array([10, 20, 30, 40, 50])
# Generate Gaussian noise with mean=0 and std=2 
noise = np.random.normal(0, 2, arr.shape)
# Add noise to the original array
noisy_arr = arr + noise

print("Original array:", arr)
print("Noise:", noise)
print("Noisy array:", noisy_arr)

Original array: [10 20 30 40 50]
Noise: [-0.25959816  0.78876002  0.88281803  3.12554988  2.01901774]
Noisy array: [ 9.74040184 20.78876002 30.88281803 43.12554988 52.01901774]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [242]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
diagonal = np.diagonal(matrix)

print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal)

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [244]:
arr = np.random.randn(100) * 20 + 30
clipped_arr = np.clip(arr, 10, 50)
clipped_arr

array([10.        , 44.86039874, 10.        , 50.        , 36.60274159,
       10.        , 28.86580416, 33.59382208, 38.34036289, 10.        ,
       50.        , 18.97728286, 50.        , 50.        , 37.16596346,
       20.07869109, 10.        , 17.78709669, 41.33225491, 28.87309895,
       35.12118755, 10.        , 32.13998982, 10.        , 26.79051538,
       20.92777473, 50.        , 25.056907  , 50.        , 44.63665111,
       10.        , 10.        , 31.24312699, 10.        , 20.75925558,
       10.        , 39.41648378, 43.8677117 , 13.61703215, 19.51540193,
       50.        , 20.25234753, 18.3572949 , 10.        , 42.91997354,
       13.42768998, 50.        , 48.6490247 , 10.        , 41.85899099,
       34.98452588, 48.84132227, 50.        , 30.38691169, 41.75755904,
       15.65693462, 23.945186  , 32.43783542, 50.        , 27.00125085,
       21.06056089, 50.        , 25.10323954, 23.11903912, 16.20166464,
       50.        , 13.61282263, 10.        , 50.        , 36.04


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [246]:
arr = np.array([[3, -1, 4],
                [-5, 9, -2],
                [7, -8, 0]])

print("Original array:\n", arr)
arr[arr < 0] = 0
print("\nArray after replacing negatives with zero:\n", arr)

Original array:
 [[ 3 -1  4]
 [-5  9 -2]
 [ 7 -8  0]]

Array after replacing negatives with zero:
 [[3 0 4]
 [0 9 0]
 [7 0 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [248]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
inner_product = np.inner(a, b)
outer_product = np.outer(a, b)
print("Array a:", a)
print("Array b:", b)
print("\nInner product:", inner_product)
print("\nOuter product:\n", outer_product)

Array a: [1 2 3]
Array b: [4 5 6]

Inner product: 32

Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [250]:
points = np.array([[0, 0],
                   [3, 4],
                   [6, 8]])

# Compute the differences between points using broadcasting
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]  # Shape: (3, 3, 2)

# Square the differences and sum over the last dimension (coordinates)
sq_dist = np.sum(diff ** 2, axis=-1)

# Take square root to get Euclidean distances
distances = np.sqrt(sq_dist)

print("Points:\n", points)

Points:
 [[0 0]
 [3 4]
 [6 8]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [252]:
dtype = [('name', 'U10'),   
         ('age', 'i4'),    
         ('height', 'f4')]  
data = np.array([('Alice', 25, 5.5),
                 ('Bob', 30, 6.1),
                 ('Charlie', 22, 5.8)], dtype=dtype)

print(data)
print("\nNames:", data['name'])
print("Ages:", data['age'])
print("Heights:", data['height'])

[('Alice', 25, 5.5) ('Bob', 30, 6.1) ('Charlie', 22, 5.8)]

Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 22]
Heights: [5.5 6.1 5.8]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [254]:
matrix = np.random.randint(0, 10, size=(5, 5))
print("Matrix:\n", matrix)
unique_values, counts = np.unique(matrix, return_counts=True)

print("\nUnique values:", unique_values)
print("Counts:", counts)

Matrix:
 [[7 4 6 4 0]
 [0 3 9 0 2]
 [0 7 8 9 7]
 [0 7 3 8 9]
 [9 5 7 6 5]]

Unique values: [0 2 3 4 5 6 7 8 9]
Counts: [5 1 2 2 2 2 5 2 4]



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [256]:
arr = np.random.rand(3, 3)  
print("Original array:\n", arr)

row_means = np.mean(arr, axis=1, keepdims=True)
centered_arr = arr - row_means

print("\nRow-wise means:\n", row_means)
print("\nArray after subtracting row means:\n", centered_arr)

Original array:
 [[0.56299008 0.51065583 0.608208  ]
 [0.78757325 0.4866824  0.48632025]
 [0.84615904 0.26579739 0.52841041]]

Row-wise means:
 [[0.56061797]
 [0.58685863]
 [0.54678895]]

Array after subtracting row means:
 [[ 0.00237211 -0.04996214  0.04759003]
 [ 0.20071462 -0.10017623 -0.10053838]
 [ 0.29937009 -0.28099156 -0.01837853]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [258]:
arr = np.random.randint(0, 101, size=10)

print("Array:\n", arr)
any_greater_than_50 = np.any(arr > 50)

print("\nAny value greater than 50?:", any_greater_than_50)

Array:
 [30  6 62 18 79  2  1 47 79 23]

Any value greater than 50?: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [261]:
arr = np.array([10, 20, 30, 40, 50, 60])
window = 3
# Number of values to compute
n = len(arr) - window + 1
moving_avg = np.array([np.mean(arr[i:i+window]) for i in range(n)])

print("Original array:", arr)
print("Moving average:", moving_avg)

Original array: [10 20 30 40 50 60]
Moving average: [20. 30. 40. 50.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [263]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

corr_matrix = np.corrcoef(x, y)
pearson_corr = corr_matrix[0, 1]

print("Pearson correlation coefficient:", pearson_corr)

Pearson correlation coefficient: 0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [265]:
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)

print("Radians:", radians)
print("Degrees:", degrees)

Radians: [0.         0.52359878 0.78539816 1.57079633 3.14159265]
Degrees: [  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [267]:
arr = np.random.randint(1,20, size=15)
var_arr = np.var(arr)
std_arr = np.std(arr)
print("The array",arr)
print("The variance of array",var_arr)
print("The standard deviation of array",std_arr)

The array [ 1 17  9 13 11  8  2 15 10  9  3 14  3  9  1]
The variance of array 25.955555555555556
The standard deviation of array 5.094659513211413



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [273]:
arr = np.array([[3, 7, 5],
                [9, 2, 6],
                [4, 8, 1]])
max_indices_col = np.argmax(arr, axis=0)
max_indices_row = np.argmax(arr, axis=1)

print("Array:\n", arr)
print("Indices of max values along columns (axis=0):", max_indices_col)
print("Indices of max values along rows (axis=1):", max_indices_row)

Array:
 [[3 7 5]
 [9 2 6]
 [4 8 1]]
Indices of max values along columns (axis=0): [1 2 1]
Indices of max values along rows (axis=1): [1 0 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [269]:
matrix = np.array([[4, 7],
                   [2, 6]])

inverse = np.linalg.inv(matrix)
print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse)

Original matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [275]:
arr = np.random.rand(10) 
standardized_arr = (arr - np.mean(arr)) / np.std(arr)

print("Original array:", arr)
print("Standardized array:", standardized_arr)
print("Mean of standardized array:", np.mean(standardized_arr))
print("Std dev of standardized array:", np.std(standardized_arr))

Original array: [0.92530203 0.19615528 0.60012874 0.8863821  0.8265917  0.03730842
 0.43895072 0.58393927 0.93812715 0.29403526]
Standardized array: [ 1.14669193 -1.22450224  0.08922438  1.02012384  0.82568472 -1.74107418
 -0.43492851  0.03657605  1.18839936 -0.90619536]
Mean of standardized array: -1.4432899320127036e-16
Std dev of standardized array: 0.9999999999999999



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [277]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
add_result = a + b
sub_result = a - b

print("Array a:", a)
print("Array b:", b)
print("Addition (a + b):", add_result)
print("Subtraction (a - b):", sub_result)

Array a: [1 2 3 4]
Array b: [10 20 30 40]
Addition (a + b): [11 22 33 44]
Subtraction (a - b): [ -9 -18 -27 -36]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [279]:
arr = np.random.rand(10)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of maximum element:", max_index)
print("Maximum element:", arr[max_index])

Array: [0.03497751 0.74265161 0.45713271 0.16550929 0.45220415 0.19534009
 0.04664267 0.04077736 0.31060623 0.32700099]
Index of maximum element: 1
Maximum element: 0.7426516084728279



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [281]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
rotated_arr = np.rot90(arr)

print("Original array:\n", arr)
print("Array rotated by 90 degrees:\n", rotated_arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array rotated by 90 degrees:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [283]:
matrix = np.array([[1, 2],
                   [3, 4]])
fro_norm = np.linalg.norm(matrix, 'fro')

print("Matrix:\n", matrix)
print("Frobenius norm:", fro_norm)

Matrix:
 [[1 2]
 [3 4]]
Frobenius norm: 5.477225575051661



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [271]:
arr_3d = np.arange(27).reshape((3, 3, 3))
print("Original 3D array:\n", arr_3d)
subarray = arr_3d[:, :, :2]
print("Sliced subarray:\n", subarray)

Original 3D array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Sliced subarray:
 [[[ 0  1]
  [ 3  4]
  [ 6  7]]

 [[ 9 10]
  [12 13]
  [15 16]]

 [[18 19]
  [21 22]
  [24 25]]]



---